name: XMLParser

on:
    push:
      branches-ignores:
        - "ga-ignore-**"
    pull_request:
      branches-ignores:
        - "ga-ignores-**"


env:
  MAX_SIZE: 30000000

jobs:
  check_repository_cleanliness:
    runs-on: ubuntu-latest
    name: check_repository_cleanliness
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check file existence
        run: FIND=$(find . -name "#*#" -o -name "*~" -o -name "*.o" -o -name "*.a" -o -name "*.so" -o -name "*.gcno" -o -name "*.gcda" -o -name "*.gcov" -o -wholename "*/tmp/*"); if [[ $FIND != "" ]]; then for element in $FIND; do echo "::error file=$element,line=1,title=Unwanted file detected::$element"; done; exit 1; fi

  check_repo_size:
      runs-on: ubuntu-latest
      needs: check_repository_cleanliness
      name: check_repo_size
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: get_size
          run: SIZE=$(du -bs --exclude=".git" | cut -f1); if [[ "$SIZE" -le "${{ env.MAX_SIZE }}" ]]; then echo "Size OK"; else echo "::error Repo size is too big (>30Mb)"; fi

  check_program_compilation:
    runs-on: ubuntu-latest
    needs: check_repository_cleanliness
    name: check_program_compilation
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Make
        run: "make"
      - name: Make clean
        run: "make clean"
